# Generated by Django 3.1.2 on 2020-10-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='group',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
