# Generated by Django 3.1.2 on 2020-10-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_solution_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='group',
            field=models.CharField(choices=[('datastructures', 'datastructures'), ('algorithms', 'algorithms'), ('problemsolving', 'problemsolving'), ('python', 'python'), ('java', 'java'), ('interview', 'interview'), ('c', 'c'), ('c++', 'c++')], default='choose', max_length=30),
        ),
    ]
